---
chromedriver_latest_release_url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
chromedriver_path: /usr/bin/chromedriver
chromedriver_tmp_dir: /tmp/chromedriver_linux64
chromedriver_tmp_path: /tmp/chromedriver_linux64.zip
chromedriver_url: https://chromedriver.storage.googleapis.com/{{chromedriver_version}}/chromedriver_linux64.zip
chromedriver_use_latest: true
chromedriver_version: 85.0.4183.87
