---
- name: Open TCP port 80 via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script
- name: Open TCP port 443 via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script
- name: Open TCP port 5222 via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: 5222
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script
- name: Open TCP port 6222 via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: 6222
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script

- name: Open UDP port 10000 via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: udp
    destination_port: 10000
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script
- name: Open telegraf prometheus port via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: "9126"
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script

- name: Open loki syslog TCP port 9000 via iptables
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: 9000
    jump: ACCEPT
    action: insert
    comment: Added via ansible post-launch configuration script

- name: Save newly added iptable rules # noqa no-changed-when
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
