---
top_level_domain: jitsi.net
vector_apt_repo: deb https://apt.vector.dev stable vector-0
vector_cloud_instance_id: "{{ cloud_instance_id | default('default') }}"
vector_cloud_region: "{{ oracle_region }}"
vector_configure_flag: true
vector_install_flag: true
vector_loki_url: "https://{{ hcv_environment}}-{{oracle_region }}-loki.{{ top_level_domain }}"
vector_shard_name: "{{ shard_name }}"
vector_shard_role: "{{ shard_role | default('vector') }}"
vector_nginx_enabled: false
vector_nginx_service_name: "nginx"
vector_nginx_access_log_paths:
  - "/var/log/nginx/access.log"
vector_nginx_error_log_paths:
  - "/var/log/nginx/error.log"
