---
hcv_environment: "all"
# rsyslog_action_file_template: "%rawmsg%\n"
# rsyslog_priv_drop_to_user: syslog
# rsyslog_priv_drop_to_group: syslog
items: []
# rsyslog configuration defaults
log_syslog_port: 514
logstash_endpoint: "{{ logstash_endpoint_domain }}"
rsyslog_abort_on_unclean_config: "off"
rsyslog_action_file_default_template: RSYSLOG_FileFormat
rsyslog_default_config: "True"
rsyslog_file_create_mode: "0640"
rsyslog_file_mode: "0640"
rsyslog_include_path: "/etc/rsyslog.d"
rsyslog_inet6_input_enabled: false
rsyslog_install_flag: true
rsyslog_known_programs: ["kernel", "ntpd", "prosody", "ansible", "JVB", "Jicofo", "monitor-terminating-instance"]
rsyslog_local_log_directory: "/var/log/local/"
rsyslog_main_config: "/etc/rsyslog.conf"
rsyslog_os_supported: false
rsyslog_repeated_msg_reduction: "off"
rsyslog_tcp_input_port: "{{ log_syslog_port }}"
rsyslog_tcp_server_enabled: true
rsyslog_udp_input_port: "{{ log_syslog_port }}"
rsyslog_udp_server_enabled: true
rsyslog_umask: "0022"
shard_name: false
