---
shard_ws_proxy_install_flag: true
shard_ws_proxy_configure_flag: true
shard_ws_proxy_domain_name: "{{ environment_domain_name }}"
shard_ws_proxy_nginx_port: "{{ shard_ws_proxy_port | default(8089) }}"
shard_ws_proxy_signal_dest_port: 443
shard_ws_proxy_region: "{{ oracle_region | default('unknown') }}"
shard_ws_proxy_host: "{{ ansible_hostname.split('.')[0] }}"
shard_ws_proxy_access_log: /var/log/nginx/access.log
shard_ws_proxy_error_log: /var/log/nginx/error.log
