---
- name: Install shard-ws-proxy nginx site config
  ansible.builtin.template:
    src: nginx.site.j2
    dest: "/etc/nginx/sites-available/shard-ws-proxy"
    mode: "0644"
  notify: Restart nginx for shard-ws-proxy

- name: Remove nginx default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove nginx default configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Enable shard-ws-proxy nginx site config
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/shard-ws-proxy"
    dest: "/etc/nginx/sites-enabled/shard-ws-proxy"
    state: link
  notify: Restart nginx for shard-ws-proxy

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
