---
- name: Install placeholder shard-ws-proxy nginx site config
  ansible.builtin.copy:
    content: "# Placeholder - consul-template will populate this file\n"
    dest: "/etc/nginx/sites-available/shard_ws.conf"
    mode: "0644"
    force: false

- name: Remove nginx default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove nginx default configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Enable shard-ws-proxy nginx site config
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/shard_ws.conf"
    dest: "/etc/nginx/sites-enabled/shard_ws.conf"
    state: link
  notify: Restart nginx for shard-ws-proxy

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
